[package]
name = "mount_type_cache_sandbox"
version = "0.1.0"
authors = ["Tsubasa Namiki"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.123"
serde_json = "1.0"
