on: [push]

name: Build

jobs:
  app:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: docker-builder
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=yearmonth::$(/bin/date -u "+%Y%m")"
          echo "::set-output name=timestamp::$(/bin/date -u "+%s")"
      - name: Get builder
        id: get-builder
        run: echo "::set-output name=container::buildx_buildkit_${{ steps.docker-builder.outputs.name }}0"
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-buildx002-${{ steps.get-date.outputs.yearmonth }}-${{ steps.get-date.outputs.timestamp }}
          restore-keys: |
            ${{ runner.os }}-buildx002-${{ steps.get-date.outputs.yearmonth }}-
          path: /tmp/buildx-cache
      - name: Exists cache
        id: exists-cache
        run: echo "::set-output name=buildx::$(test -d /tmp/buildx-cache && echo true)"
      - name: Restore buildkit cache
        # cache-hit is true only equals key exactly
        # if: steps.buildx-cache.outputs.cache-hit == 'true'
        if: steps.exists-cache.outputs.buildx == 'true'
        run: |
          echo && echo "============ Before restoring"
          docker buildx du --verbose
          echo && echo "============ Restore buildkit cache"
          docker buildx stop
          docker run --rm --volumes-from ${{ steps.get-builder.outputs.container }} \
            -v /tmp/buildx-cache:/backup \
            alpine tar xvf /backup/buildkit.tar.gz -C /var/lib
          docker buildx inspect --bootstrap
          echo && echo "============ After restoring"
          docker buildx du --verbose
      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          builder: ${{ steps.docker-builder.outputs.name }}
          context: .
          push: false
          cache-from: |
            type=local,src=/tmp/buildx-cache/layer
          cache-to: |
            type=local,mode=max,dest=/tmp/buildx-cache/layer
          tags: |
            app:latest
      - name: Backup buildkit cache
        env:
          KEEP_STORAGE: 1073741824 # this is 1GB
        run: |
          echo && echo "============ Before pruning"
          docker buildx du --verbose
          echo && echo "============ Start pruning"
          docker buildx prune --force --filter type=frontend
          docker buildx prune --force --filter type=regular
          docker buildx prune --force --filter type=source.local 
          docker buildx prune --force --keep-storage ${KEEP_STORAGE}
          echo && echo "============ After pruning"
          docker buildx du --verbose
          echo && echo "============ Backup buildkit cache"
          docker run --rm --volumes-from ${{ steps.get-builder.outputs.container }} \
            -v /tmp/buildx-cache:/backup \
            alpine tar cvf /backup/buildkit.tar.gz -C /var/lib buildkit
      # - uses: mxschmitt/action-tmate@v3
      #   if: ${{ failure() }}
